### ISSUE TITLE
Enable linting and prettier

### ISSUE THREAD

**Issue by TomSmith27** [3Squared/ForgeUI#24]

**Comment by Polymeta** [comment]
When you say enable linting. Do you mean as a step in the workflow to use as a validation for PRs so they fail and get fixed before merging?

**Comment by TomSmith27** [comment]
Yep exactly, i dont think we have any linting setup in the project, so set it up for Dev but also as part of the build step

**Comment by Polymeta** [comment]
Ah cool, and you plan to have all the eslint stuff in that shared-configuration package?
