### ISSUE TITLE
When tapping on navbar hamburger menu, other navbar hamburger menus on the page open/close

### ISSUE THREAD

**Issue by hardeepsidhu9** [3Squared/ForgeUI#36]
Can see this clearly on the navbar page in the forge ui style guide. https://saforgestyleguide.z33.web.core.windows.net/#/layout/navbar/navbar
SETUP: 
we have multiple navbars on a page and reduce the window size horizontally so that the hamburger option appears
ACTION:
Toggle the hamburger option on one of the navbars
EXPECTED:
Navbar options open ONLY for the navbar hamburger button clicked
ACTUAL:
the navbar options open for ALL the navbars on the screen

Before click:
![image](https://user-images.githubusercontent.com/89470268/213680049-58c9e6d3-8a6c-4c8c-a6d4-dc478b41ea10.png)
After click:
![image](https://user-images.githubusercontent.com/89470268/213680089-849a4043-21ff-47a1-94b1-42b0f111fa72.png)

**Comment by TomSmith27** [comment]
@hardeepsidhu9 thanks for raising this issue 🎉 , that is actually the old version of the documentation, This issue would need to be fixed in the RailSmart Design System. @JakeMinor Can fix this
